apiVersion: v1
kind: Service
metadata:
  name: shop-backend
  labels:
    app: shop-backend
spec:
  type: LoadBalancer
  ports:
    - port: 3030
  selector:
    app: shop-backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shop-backend-deployment
  labels:
    app: shop-backend
spec:
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
      - image: DOCKERHUB_USERNAME/codepattern-backend:latest
        imagePullPolicy: Always
        name: shop-backend
        ports:
        - containerPort: 3030
        env:
          - name: ORGID
            value: "org.ShopOrg"
          - name: DOCKER_SOCKET_PATH
            value: "tcp://docker:2375"
          - name: DOCKER_CCENV_IMAGE
            value: "hyperledger/fabric-ccenv:x86_64-1.0.6"
          - name: SECRETSDIR
            value: "/host/var/run/secrets"
          - name: RABBITMQQUEUE
            value: "seller_queue"
          - name: SOCKETPORT
            value: "3030"
          - name: MESSAGEEXPIRY
            value: "400"
          - name: EVENTEMITTER
            value: "true"
          - name: SENDTOIOT
            value: "false"
          - name: SCALECLIENT
            value: "1"
        volumeMounts:
          - name: secret-volume
            mountPath: /host/var/run/secrets
      volumes:
        - name: secret-volume
          secret:
            secretName: secret-files
            items:
              - key: config.json
                path: config
              - key: channel.tx
                path: channel
