apiVersion: v1
kind: Service
metadata:
  name: shop-peer
  labels:
    app: shop-peer
spec:
  type: ClusterIP
  ports:
    - port: 7051
      name: shop-port-1
    - port: 7053
      name: shop-port-2
  selector:
    app: shop-peer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shop-peer-deployment
  labels:
    app: shop-peer
spec:
  template:
    metadata:
      labels:
        app: shop-peer
    spec:
      containers:
      - image: DOCKERHUB_USERNAME/codepattern-shop-peer:latest
        imagePullPolicy: Always
        workingDir: /peer
        command: ["peer"]
        args: ["node", "start", "--peer-defaultchain=false"]
        name: shop-peer
        ports:
        - containerPort: 7051
        - containerPort: 7053
        env:
          - name: CORE_PEER_ID
            value: "shop-peer"
          - name: CORE_PEER_ADDRESS
            value: "shop-peer:7051"
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: "shop-peer:7051"
          - name: CORE_PEER_LOCALMSPID
            value: "ShopOrgMSP"
          - name: CORE_LEDGER_STATE_STATEDATABASE
            value: "CouchDB"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
            value: "shop-statedb:5984"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
            value: ""
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
            value: ""
          - name: CORE_VM_ENDPOINT
            value: "tcp://docker:2375"
          - name: CORE_LOGGING_LEVEL
            value: "DEBUG"
          - name: CORE_PEER_TLS_ENABLED
            value: "false"
          - name: CORE_PEER_ENDORSER_ENABLED
            value: "true"
          - name: CORE_PEER_GOSSIP_USELEADERELECTION
            value: "true"
          - name: CORE_PEER_GOSSIP_ORGLEADER
            value: "false"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          - name: CORE_PEER_MSPCONFIGPATH
            value: "/peer/crypto/msp"
          - name: CORE_PEER_ADDRESSAUTODETECT
            value: "true"
          - name: CORE_PEER_NETWORKID
            value: "nid1"
          - name: CORE_PEER_LISTENADDRESS
            value: 0.0.0.0:7051
          - name: CORE_PEER_EVENTS_ADDRESS
            value: 0.0.0.0:7053
          - name: GODEBUG
            value: "netdns=go"
          - name: CORE_VM_DOCKER_ATTACHSTDOUT
            value: "true"
        volumeMounts:
          - name: shop-peer-storage
            mountPath: /var/hyperledger/production
            subPath: shop-peer
      volumes:
        - name: shop-peer-storage
          persistentVolumeClaim:
            claimName: peer-claim
