apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-volume
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: couchdb-claim
  nfs:
    server: "NFS_SERVER"
    path: "/NFS_PATH"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "" # Comment this line to use dynamic provisioning (paid)
  name: couchdb-claim
  labels:
    app: couchdb-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
